In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [7]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.size)

5


In [10]:
pydoc numpy.add

SyntaxError: invalid syntax (254710804.py, line 1)

In [16]:
arr = np.zeros((2, 6))
arr[:] = 1
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [20]:
arr = np.arange(10, 50)
reserved = arr[::-1]
reserved

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [23]:
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4]),)
