In [2]:
import json

In [3]:
def load_data(data):
    with open(data, "r") as f:
        data = json.load(f)
    return data

In [4]:
data= load_data("store_data.json")
print(data)

[{'name': 'Alice', 'rating': '5', 'feedback': 'Great product!!', 'age': '25'}, {'name': 'Bob', 'rating': 'four', 'feedback': 'ok but late Delivery', 'age': '30'}, {'name': 'Charlie', 'rating': 'two', 'feedback': 'BAD EXPERIENCE'}, {'name': 'Diana', 'feedback': 'Loved it!', 'rating': '5', 'age': '28'}, {'name': 'Eve', 'rating': '3.5', 'feedback': 'Average – could be better', 'age': '20'}, {'name': 'Alice', 'rating': '5', 'feedback': 'Great product again!', 'age': '25'}]


In [5]:
def clean_data(data):
    for user in data:
        print(user)

In [6]:
clean_data(data)

{'name': 'Alice', 'rating': '5', 'feedback': 'Great product!!', 'age': '25'}
{'name': 'Bob', 'rating': 'four', 'feedback': 'ok but late Delivery', 'age': '30'}
{'name': 'Charlie', 'rating': 'two', 'feedback': 'BAD EXPERIENCE'}
{'name': 'Diana', 'feedback': 'Loved it!', 'rating': '5', 'age': '28'}
{'name': 'Eve', 'rating': '3.5', 'feedback': 'Average – could be better', 'age': '20'}
{'name': 'Alice', 'rating': '5', 'feedback': 'Great product again!', 'age': '25'}


In [7]:
def clean_data(data):
    text_to_num = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5}
    cleaned_data = []
    unique_users = set()
    for user in data:
        # Clean rating - data consistency
        raw_rating = str(user["rating"]).strip().lower()
        if raw_rating in text_to_num:
            raw_rating = text_to_num[raw_rating]
        user["rating"] = raw_rating
        # print(raw_rating)

        # Handling massing values
        raw_age = user.get("age")
        if raw_age == None:
            user["age"] = None

        # Deduplication
        if(user["name"].strip() in unique_users):
            continue
        unique_users.add(user["name"])
        cleaned_data.append(user)
    return cleaned_data

In [8]:
clean_data(data)

[{'name': 'Alice', 'rating': '5', 'feedback': 'Great product!!', 'age': '25'},
 {'name': 'Bob', 'rating': 4, 'feedback': 'ok but late Delivery', 'age': '30'},
 {'name': 'Charlie', 'rating': 2, 'feedback': 'BAD EXPERIENCE', 'age': None},
 {'name': 'Diana', 'feedback': 'Loved it!', 'rating': '5', 'age': '28'},
 {'name': 'Eve',
  'rating': '3.5',
  'feedback': 'Average – could be better',
  'age': '20'}]

In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [11]:
# arr1 = np.arange(1, 51)
# print(arr1)

arr2 = np.linspace(1, 50, 41)
print(arr2)

[ 1.     2.225  3.45   4.675  5.9    7.125  8.35   9.575 10.8   12.025
 13.25  14.475 15.7   16.925 18.15  19.375 20.6   21.825 23.05  24.275
 25.5   26.725 27.95  29.175 30.4   31.625 32.85  34.075 35.3   36.525
 37.75  38.975 40.2   41.425 42.65  43.875 45.1   46.325 47.55  48.775
 50.   ]


In [12]:
arr1 = np.zeros((4,4))
print(arr1)

arr2 = np.eye(3)
print(arr2)

arr3 = np.full((2,5), 9)
print(arr3)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[9 9 9 9 9]
 [9 9 9 9 9]]


In [13]:
arr = np.array([1, 2.5, 3, 4.7], dtype="int64")
arr.dtype


dtype('int64')

In [14]:
arr = np.array([[1,2,3], [4,5,6],[7,8,9], [10,11,12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)



(4, 3)
12
2
int64
8


In [15]:
arr = np.array([1,2,3,4,5,6,7,8])
reshaped_arr =arr.reshape(2, 4)
print(reshaped_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][2])
print(arr[1][0])
print(arr[:, 1])

# [30, 40, 50]
a = np.array([10,20,30,40,50,60])
print(a[2:5])

#using the fancy indexing
idx = [0, 3, 5]
print(a[idx])

30
40
[20 50 80]
[30 40 50]
[10 40 60]


In [17]:
arr = np.array([1,2,3,4,5,6])
print(arr[arr % 2 == 0])
print(arr[arr > 3])


[2 4 6]
[4 5 6]


In [18]:
arr = np.array([10, 20, 30, 40, 50])

view_arr = arr[1:4].copy()

view_arr[1] = 777

print("Original Array: ", arr)
print("Modified view array: ", view_arr)

Original Array:  [10 20 30 40 50]
Modified view array:  [ 20 777  40]


In [30]:
# 3D Dimensional Array - 

# arr3D = np.array([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
# print(arr3D, arr3D.shape)

# print(arr3D[1][0][2])

# print(arr3D[:, 0, 1])

arr_3D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_3D)

print(arr_3D.sum(axis=1))
print(arr_3D.sum(axis=0))

print(arr_3D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[12 15 18]


In [31]:
# Broadcasting -
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[10, 20, 30, 40, 50], [6, 7, 8, 9, 10]])

print(arr + arr2)

[[11 22 33 44 55]
 [ 7  9 11 13 15]]


In [34]:
print(np.round(3.49))

3.0


In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("globalAirQuality.csv")

In [5]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017


In [9]:
if (df == "Delhi").any().any():
    print("Delhi exists as a value")
else:
    print("Delhi NOT found as a value")

Delhi exists as a value


In [11]:
rows_with_delhi = df[df["city"].str.contains("Delhi", case=False, na=False)]
print(rows_with_delhi)

                       timestamp country   city  latitude  longitude    pm25  \
6840  2025-11-04 18:25:17.554219      IN  Delhi    28.704     77.102  44.829   
6841  2025-11-04 19:25:17.554219      IN  Delhi    28.704     77.102  38.797   
6842  2025-11-04 20:25:17.554219      IN  Delhi    28.704     77.102  54.364   
6843  2025-11-04 21:25:17.554219      IN  Delhi    28.704     77.102  26.080   
6844  2025-11-04 22:25:17.554219      IN  Delhi    28.704     77.102  18.285   
...                          ...     ...    ...       ...        ...     ...   
7195  2025-11-19 13:25:17.554219      IN  Delhi    28.704     77.102  16.101   
7196  2025-11-19 14:25:17.554219      IN  Delhi    28.704     77.102  48.989   
7197  2025-11-19 15:25:17.554219      IN  Delhi    28.704     77.102  37.461   
7198  2025-11-19 16:25:17.554219      IN  Delhi    28.704     77.102  77.418   
7199  2025-11-19 17:25:17.554219      IN  Delhi    28.704     77.102  62.481   

         pm10     no2    so2      o3   

In [12]:
rows_with_delhi.head(5)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6840,2025-11-04 18:25:17.554219,IN,Delhi,28.704,77.102,44.829,28.334,9.180,6.874,49.548,0.911,89,33.540,40.150,7.473
6841,2025-11-04 19:25:17.554219,IN,Delhi,28.704,77.102,38.797,54.046,53.594,3.407,40.532,0.454,133,23.468,30.788,2.936
6842,2025-11-04 20:25:17.554219,IN,Delhi,28.704,77.102,54.364,131.193,34.506,3.664,48.325,1.211,131,16.154,55.117,2.934
6843,2025-11-04 21:25:17.554219,IN,Delhi,28.704,77.102,26.080,61.262,8.017,6.116,47.416,0.908,61,35.881,86.602,6.232
6844,2025-11-04 22:25:17.554219,IN,Delhi,28.704,77.102,18.285,54.259,43.646,6.036,47.786,0.409,109,37.776,55.852,6.343


In [25]:
df.loc[[6840, 6841]]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6840,2025-11-04 18:25:17.554219,IN,Delhi,28.704,77.102,44.829,28.334,9.180,6.874,49.548,0.911,89,33.540,40.150,7.473
6841,2025-11-04 19:25:17.554219,IN,Delhi,28.704,77.102,38.797,54.046,53.594,3.407,40.532,0.454,133,23.468,30.788,2.936


In [29]:
tempreture = rows_with_delhi.query("temperature > 30")
tempreture = rows_with_delhi.query("temperature > 30")[["country", "city", "aqi", "temperature"]] #Chaining Comparision

In [30]:
tempreture.head(5)

,country,city,aqi,temperature
2,US,New York,84,31.833
6,US,New York,155,36.729
7,US,New York,115,37.891
14,US,New York,121,34.481
17,US,New York,127,36.193


In [18]:
rows_with_newYork = df[df["city"].str.contains("New York", case=False, na=False)]

In [28]:
rows_with_newYork

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2025-11-19 13:25:17.554219,US,New York,40.713,-74.006,61.772,86.867,54.213,9.098,40.769,0.641,135,35.176,52.584,6.478
356,2025-11-19 14:25:17.554219,US,New York,40.713,-74.006,61.468,49.062,55.001,6.786,45.899,0.764,137,33.195,44.607,9.578
357,2025-11-19 15:25:17.554219,US,New York,40.713,-74.006,32.985,47.756,32.260,5.322,70.712,0.814,80,8.260,60.976,5.767
358,2025-11-19 16:25:17.554219,US,New York,40.713,-74.006,22.031,65.374,67.655,9.725,7.731,0.610,169,32.219,71.595,3.734


In [36]:
string = "     nobitamestry@gmail.com   "


print(string.split("@"))

print(string.strip())

['     nobitamestry', 'gmail.com   ']
nobitamestry@gmail.com


# Practice Problem about the series

In [1]:
import pandas as pd

In [3]:
s = pd.Series([2, 4, 6, 8, 10])
print(s)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
s = pd.Series(arr)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [7]:
info = {'a': 100, 'b': 200, 'c': 300, 'd': 400}
s = pd.Series(info)
print(s)

a    100
b    200
c    300
d    400
dtype: int64


In [8]:
s = pd.Series([10, 20, 30, 40, 50])
converted_list = s.tolist()
print(converted_list)

[10, 20, 30, 40, 50]


In [10]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print(s1 + s2 )

0     3
1     7
2    11
3    15
4    19
dtype: int64


In [11]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print(f"Add the two Series: {s1 + s2}")
print(f"Subtraction: {s1 - s2}")
print(f"Multiplication: {s1 * s2}")
print(f"Divide: {s1 / s2}")

Add the two Series: 0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction: 0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication: 0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide: 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [12]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print( s1 == s2 )
print( s1 < s2 )
print( s1 > s2 )


0    False
1    False
2    False
3    False
4    False
dtype: bool


In [13]:
info = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
s = pd.Series(info)
print(s)

a    100
b    200
c    300
d    400
e    800
dtype: int64


In [16]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
s['python'] = 200.12
s

0            100
1            200
2         python
3         300.12
4            400
python    200.12
dtype: object

In [17]:
s = pd.Series([100, 200, 'python', 300.12, 400])
n = np.array(s)
n

array([100, 200, 'python', 300.12, 400], dtype=object)

In [24]:
s = pd.Series([10, 20, 30, 40, 50])
s = pd.concat([s, pd.Series([60])])
print(s)


0    10
1    20
2    30
3    40
4    50
0    60
dtype: int64


In [25]:
s = pd.Series([10, 20, 30, 40, 50])
s.loc[len(s)] = 60
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64


In [30]:
s = pd.Series([10, 22, 5, 30, 15])
asc = s.sort_values()
asc

s = pd.Series([10, 22, 5, 30, 15])
dsc = s.sort_values(ascending=False)
dsc

3    30
1    22
4    15
0    10
2     5
dtype: int64

In [32]:
s = pd.Series([1, 2, 3, 4, 5])
# print(s[::-1])
s_reversed = s[::-1].reset_index(drop=True)
print(s_reversed)


0    5
1    4
2    3
3    2
4    1
dtype: int64


In [33]:
s = pd.Series([1, 3, 5, 7, 9, 11, 13])
largest_3 = s.nlargest(3)
print(largest_3)

6    13
5    11
4     9
dtype: int64


In [34]:
s = pd.Series([1, 3, 5, 7, 9, 11, 13])
smallest_3 = s.nsmallest(3)
print(smallest_3)

0    1
1    3
2    5
dtype: int64


In [38]:
s = pd.Series([10, 20, 30, 40, 50])
print(s.count())

5


In [39]:
s = pd.Series([1, 2, 3, 4, 5])
print(s.dtype)

int64
